

flutter_application_path = '../flutter_module_ariel'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'testando' do
    install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
end
